export const HTTP_STATUS = {
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
} as const;

export const HTTP_STATUS_RANGE = {
  CLIENT_ERROR_START: 400,
  SERVER_ERROR_START: 500,
} as const;
