/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ProtectedRouteRouteImport } from "./routes/_protected/route";
import { Route as ProtectedIndexRouteImport } from "./routes/_protected/index";
import { Route as ProtectedGoalsIndexRouteImport } from "./routes/_protected/goals/index";
import { Route as ProtectedGoalsGoalIdIndexRouteImport } from "./routes/_protected/goals/$goalId/index";

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: "/_protected",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProtectedRouteRoute,
} as any);
const ProtectedGoalsIndexRoute = ProtectedGoalsIndexRouteImport.update({
  id: "/goals/",
  path: "/goals/",
  getParentRoute: () => ProtectedRouteRoute,
} as any);
const ProtectedGoalsGoalIdIndexRoute =
  ProtectedGoalsGoalIdIndexRouteImport.update({
    id: "/goals/$goalId/",
    path: "/goals/$goalId/",
    getParentRoute: () => ProtectedRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof ProtectedIndexRoute;
  "/goals/": typeof ProtectedGoalsIndexRoute;
  "/goals/$goalId/": typeof ProtectedGoalsGoalIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof ProtectedIndexRoute;
  "/goals": typeof ProtectedGoalsIndexRoute;
  "/goals/$goalId": typeof ProtectedGoalsGoalIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_protected": typeof ProtectedRouteRouteWithChildren;
  "/_protected/": typeof ProtectedIndexRoute;
  "/_protected/goals/": typeof ProtectedGoalsIndexRoute;
  "/_protected/goals/$goalId/": typeof ProtectedGoalsGoalIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/goals/" | "/goals/$goalId/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/goals" | "/goals/$goalId";
  id:
    | "__root__"
    | "/_protected"
    | "/_protected/"
    | "/_protected/goals/"
    | "/_protected/goals/$goalId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_protected": {
      id: "/_protected";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof ProtectedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_protected/": {
      id: "/_protected/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof ProtectedIndexRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
    "/_protected/goals/": {
      id: "/_protected/goals/";
      path: "/goals";
      fullPath: "/goals/";
      preLoaderRoute: typeof ProtectedGoalsIndexRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
    "/_protected/goals/$goalId/": {
      id: "/_protected/goals/$goalId/";
      path: "/goals/$goalId";
      fullPath: "/goals/$goalId/";
      preLoaderRoute: typeof ProtectedGoalsGoalIdIndexRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute;
  ProtectedGoalsIndexRoute: typeof ProtectedGoalsIndexRoute;
  ProtectedGoalsGoalIdIndexRoute: typeof ProtectedGoalsGoalIdIndexRoute;
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedGoalsIndexRoute: ProtectedGoalsIndexRoute,
  ProtectedGoalsGoalIdIndexRoute: ProtectedGoalsGoalIdIndexRoute,
};

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
